### ISSUE TITLE
404 after sending transaction

### ISSUE THREAD

**Issue by flappys** [hippospace/aptos-wallet-adapter#8]
GET https://fullnode.devnet.aptoslabs.com/v1/transactions/by_hash/ 404

Getting 404 error after submitting transaction. This used to works few days back.

**Comment by tin-snowflake** [comment]
I think this is resolved in the latest commit: https://github.com/hippospace/aptos-wallet-adapter/commit/3a634adf8834efb4c4d8ad0fe17900f00b6e5740

**Comment by flappys** [comment]
> I think this is resolved in the latest commit: [3a634ad](https://github.com/hippospace/aptos-wallet-adapter/commit/3a634adf8834efb4c4d8ad0fe17900f00b6e5740)

this still exists, same error upon running the wallet-tester dapp

**Comment by tom-hippo** [comment]
Hi, wonder if you have reinstalled the wallet extension and maybe give a try on reinstall all node_modules since sometime it is cached

**Comment by flappys** [comment]
I am not sure what am i missing from my end. Here is the error that i am getting now after updating to latest code:

I copied wallet_tester as separate project and installed the necessary modules using yarn. Added "@manahippo/aptos-wallet-adapter": "^0.3.0", to package.json. 

Also this version of wallet adapter that gets installed using 0.3.0 doesn't have Spika.

![image](https://user-images.githubusercontent.com/98147132/186968177-863af3f5-acff-4b23-8c02-fce366c06f78.png)

**Comment by tom-hippo** [comment]
Thanks for reporting. This should have been fixed in the new [commit](https://github.com/hippospace/aptos-wallet-adapter/commit/803ac8654fdb07d869c54bd2760215ae8093dd4f)

**Comment by flappys** [comment]
> Thanks for reporting. This should have been fixed in the new [commit](https://github.com/hippospace/aptos-wallet-adapter/commit/803ac8654fdb07d869c54bd2760215ae8093dd4f)

thanks Tom, I think the update is not reflected in the npm module. 0.3.0

**Comment by pisomanik** [comment]
> Thanks for reporting. This should have been fixed in the new [commit](https://github.com/hippospace/aptos-wallet-adapter/commit/803ac8654fdb07d869c54bd2760215ae8093dd4f)

This is fixed in the newer commit but I think the error message can be improved. For example, consider the transfer function below in the example of `wallet-tester` in the repo.

https://github.com/hippospace/aptos-wallet-adapter/blob/fd9093803613001975ac6d9961e282ea051245cf/packages/wallet-tester/src/pages/index.tsx#L48-L81

If I mess up the function name like from `function: '0x1::coin::transfer` to `function: '0x1::coin::transfe`. (The missing `r`) 
I get an error in the console.

```
wallet errors:  WalletSignAndSubmitMessageError: The given transaction is invalid
    at AptosWalletAdapter.<anonymous> (AptosWallet.ts:203:1)
    at Generator.next (<anonymous>)
    at fulfilled (log.js:59:1)
tx error:  undefined
```

If the error message is more aligned in terms of the standard API it would be great. Idk how the curl API call to `transfer` handles this. But need to do something about this.

I have been trying to sign and submit a payload but I can't seem to figure out if the payload is messed up or the contract is rejecting it.

PS. Happy to make a PR, please share your thoughts.
